### PR TITLE
Adds the ability to set env variables for soyuz to use

### PR DESCRIPTION
**Pull request by NickLaMuro**

### CODE REVIEW

**Comment by NickLaMuro** [comment]
@anfleene

**Comment by anfleene** [comment]
Something about this bothers me. It seems ok but eventually We should create a command builder class that figures out what kind of command it is based on the actual values of a hash. Something about how we're building the commands in general seems wrong. We're relying on what type of object it is a little too much I think.

**Comment by anfleene** [comment]
In general the code review seems fine. The tests pass so :shipit:

**Comment by NickLaMuro** [comment]
@anfleene I agree, but my guess is you wrote command choice logic, so I blame you :smile:

**Comment by anfleene** [comment]
Right. I should have built a command factory but seeing that refactoring was hard with just 2 kinds of commands.

**Comment by anfleene** [comment]
I'll add an issue. We can attack it in the future.

**Pull request merged**
